const translations = {
  en: {
    doctorSignUp: "Doctor Sign Up",
    phonePlaceholder: "Phone Number",
    namePlaceholder: "Doctor Name",
    emailPlaceholder: "Email ID",
    licensePlaceholder: "License ID",
    qualificationPlaceholder: "Qualification",
    specializationPlaceholder: "Specialization",
    otpPlaceholder: "Enter OTP",
    passwordPlaceholder: "Password",
    rePasswordPlaceholder: "Confirm Password",
    resendOTP: "Resend OTP",
    verifyOTP: "Verify OTP",
    signUpButton: "Sign Up",
    nextButton: "Next",
    alreadyAccount: "Already have an account?",
    signInLink: "Sign In",

    errors: {
      invalidPhone: "Enter a valid 10-digit phone number.",
      nameRequired: "Doctor name is required.",
      licenseRequired: "License ID is required.",
      emailInvalid: "Enter a valid email address.",
      qualificationRequired: "Qualification is required.",
      specializationRequired: "Specialization is required.",
      otpInvalid: "Invalid OTP format.",
      passwordRequired: "Password is required.",
      passwordLength: "Password must be at least 6 characters.",
      passwordMismatch: "Passwords do not match.",
    },
  },

  hi: {
    doctorSignUp: "डॉक्टर साइन अप",
    phonePlaceholder: "फोन नंबर",
    namePlaceholder: "डॉक्टर का नाम",
    emailPlaceholder: "ईमेल आईडी",
    licensePlaceholder: "लाइसेंस आईडी",
    qualificationPlaceholder: "योग्यता",
    specializationPlaceholder: "विशेषज्ञता",
    otpPlaceholder: "ओटीपी दर्ज करें",
    passwordPlaceholder: "पासवर्ड",
    rePasswordPlaceholder: "पासवर्ड की पुष्टि करें",
    resendOTP: "ओटीपी फिर से भेजें",
    verifyOTP: "ओटीपी सत्यापित करें",
    signUpButton: "साइन अप करें",
    nextButton: "आगे बढ़ें",
    alreadyAccount: "क्या आपके पास पहले से खाता है?",
    signInLink: "साइन इन करें",

    errors: {
      invalidPhone: "कृपया मान्य 10 अंकों का फ़ोन नंबर दर्ज करें।",
      nameRequired: "डॉक्टर का नाम आवश्यक है।",
      licenseRequired: "लाइसेंस आईडी आवश्यक है।",
      emailInvalid: "कृपया मान्य ईमेल पता दर्ज करें।",
      qualificationRequired: "योग्यता आवश्यक है।",
      specializationRequired: "विशेषज्ञता आवश्यक है।",
      otpInvalid: "अमान्य ओटीपी प्रारूप।",
      passwordRequired: "पासवर्ड आवश्यक है।",
      passwordLength: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
      passwordMismatch: "पासवर्ड मेल नहीं खा रहे हैं।",
    },
  },

  kn: {
    doctorSignUp: "ಡಾಕ್ಟರ್ ಸೈನ್ ಅಪ್",
    phonePlaceholder: "ಫೋನ್ ನಂಬರ್",
    namePlaceholder: "ಡಾಕ್ಟರ್ ಹೆಸರು",
    emailPlaceholder: "ಇಮೇಲ್ ಐಡಿ",
    licensePlaceholder: "ಲೈಸೆನ್ಸ್ ಐಡಿ",
    qualificationPlaceholder: "ಅರ್ಹತೆ",
    specializationPlaceholder: "ವಿಶೇಷತೆ",
    otpPlaceholder: "OTP ನಮೂದಿಸಿ",
    passwordPlaceholder: "ಗುಪ್ತಪದ",
    rePasswordPlaceholder: "ಗುಪ್ತಪದ ದೃಢೀಕರಿಸಿ",
    resendOTP: "OTP ಮರುಕಳುಹಿಸಿ",
    verifyOTP: "OTP ಪರಿಶೀಲಿಸಿ",
    signUpButton: "ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    nextButton: "ಮುಂದೆ",
    alreadyAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?",
    signInLink: "ಸೈನ್ ಇನ್ ಮಾಡಿ",

    errors: {
      invalidPhone: "ಮಾನ್ಯ 10 ಅಂಕಿಯ ಫೋನ್ ನಂಬರ್ ನಮೂದಿಸಿ.",
      nameRequired: "ಡಾಕ್ಟರ್ ಹೆಸರು ಅಗತ್ಯವಿದೆ.",
      licenseRequired: "ಲೈಸೆನ್ಸ್ ಐಡಿ ಅಗತ್ಯವಿದೆ.",
      emailInvalid: "ಮಾನ್ಯ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ.",
      qualificationRequired: "ಅರ್ಹತೆ ಅಗತ್ಯವಿದೆ.",
      specializationRequired: "ವಿಶೇಷತೆ ಅಗತ್ಯವಿದೆ.",
      otpInvalid: "ಅಮಾನ್ಯ OTP ಸ್ವರೂಪ.",
      passwordRequired: "ಗುಪ್ತಪದ ಅಗತ್ಯವಿದೆ.",
      passwordLength: "ಗುಪ್ತಪದ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಿರಬೇಕು.",
      passwordMismatch: "ಗುಪ್ತಪದಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ.",
    },
  },
};

export default translations;
